POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh1c2dhZnZlbC5lcmlrQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MDMzNTcyODF9.gwOTPRlTpYWMciQho92_Uup6m3srWwT2Gd_9OLrWrjo

{
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "title":"React patterns",
  "likes": 7
}